[package]
name = "truenas-roles-anywhere-enroll"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "truenas-roles-anywhere-enroll"
path = "src/main.rs"

[dependencies]
aws-config.workspace = true
aws-sdk-ssm.workspace = true
lambda_http.workspace = true
rcgen.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
x509-parser = { version = "0.17", features = ["verify"] }
